### ISSUE TITLE
NullPointerException in BlockPlaceEvent

### ISSUE THREAD

**Issue by VideoGameSmash12** [TotalFreedomMC/TotalFreedomMod#216]
It appears that something is borked in the BlockPlaceEvent, which is in the BlockBlocker. Here's the full stacktrace:
`:[15:30:25 ERROR]: Could not pass event BlockPlaceEvent to TotalFreedomMod v5.5java.lang.NullPointerException
	at me.totalfreedom.totalfreedommod.blocking.BlockBlocker.onBlockPlace(BlockBlocker.java:147)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor534.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:346)
	at net.minecraft.server.v1_15_R1.ItemStack.placeItem(ItemStack.java:237)
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:514)
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1414)
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105)
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1059)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974)
	at java.lang.Thread.run(Thread.java:748)`

This should be fixed.

**Comment by ncurran02** [comment]
NPE is given for this line: https://github.com/TFPatches/TotalFreedomMod/blob/server/src/main/java/me/totalfreedom/totalfreedommod/blocking/BlockBlocker.java#L147

**Comment by ajaxvp** [comment]
fixed in 1.16
